"""LQI synthesis in the space of Bryson excursions and its exact 2-DOF PIDF map.

Decision vector (Eq. (38)):  xi = [log10 Di, log10 Dv, log10 wB, log10 Kb]
    Q  = diag(Di^-2, Dv^-2, (Dv/wB)^-2),   Rd = Dd^-2,  Dd = (dmax-dmin)/2
    A_a^T P + P A_a - P B_a Rd^-1 B_a^T P + Q = 0,   K = Rd^-1 B_a^T P
Exact realization (Proposition 2):
    Kp = Kv + Ki_x/R,  Ki = -Kz,  Kd = C (Ki_x - rC Kv),  N = 1/(rC C),  b = 1, c = 0
Anti-windup (outside the linear proof, identical in both laws):
    LQI : z'  = e + (Kb/|Kz|)(d - d~)      PIDF: xI' = Ki e + Kb (d - d~)
"""
from __future__ import annotations

from dataclasses import dataclass
import numpy as np
from scipy.linalg import solve_continuous_are

from .params import PLANT, SAMP
from .plant import linearize

V_SYN = 24.0                     # synthesis equilibrium
DD = (SAMP.dmax - SAMP.dmin) / 2  # 0.48, fixed physical duty excursion
XI0 = np.log10([15.0, 46.0, 2 * np.pi * 1500.0, 2 * np.pi * 1500.0])
LB = np.array([0.0, 0.0, 2.0, 2.0])
UB = np.array([2.0, 2.4, np.log10(np.pi / SAMP.Ts), np.log10(np.pi / SAMP.Ts)])


def augmented(Vo=V_SYN, P=PLANT):
    lin = linearize(Vo, 0.0, P)
    Aa = np.zeros((3, 3))
    Aa[:2, :2] = lin.A
    Aa[2, :2] = -lin.Cy
    Ba = np.vstack([lin.Bd, [[0.0]]])
    return Aa, Ba, lin


def bryson(xi):
    Di, Dv, wB = 10.0 ** np.asarray(xi[:3], dtype=float)
    Q = np.diag([Di ** -2, Dv ** -2, (Dv / wB) ** -2])
    Rd = np.array([[DD ** -2]])
    return Q, Rd


@dataclass
class LQIDesign:
    xi: np.ndarray
    Q: np.ndarray
    Rd: np.ndarray
    P: np.ndarray
    K: np.ndarray            # [Ki_x, Kv_x, Kz]
    care_res: float
    care_res_rel: float
    poles: np.ndarray
    Kb: float
    theta: np.ndarray        # (Kp, Ki, Kd, N, b, c, Kb)


def lqi(xi, Vo=V_SYN, P=PLANT) -> LQIDesign:
    Aa, Ba, _ = augmented(Vo, P)
    Q, Rd = bryson(xi)
    X = solve_continuous_are(Aa, Ba, Q, Rd)
    K = (np.linalg.solve(Rd, Ba.T @ X)).ravel()
    res = Aa.T @ X + X @ Aa - X @ Ba @ np.linalg.solve(Rd, Ba.T) @ X + Q
    poles = np.linalg.eigvals(Aa - Ba @ K[None, :])
    Kb = 10.0 ** float(xi[3])
    return LQIDesign(np.asarray(xi, float), Q, Rd, X, K,
                     float(np.linalg.norm(res)),
                     float(np.linalg.norm(res) / np.linalg.norm(Q)),
                     poles, Kb, pidf_map(K, Kb, P))


def pidf_map(K, Kb, P=PLANT):
    """Proposition 2: exact nominal 2-DOF PIDF realization of the LQI gain."""
    Kix, Kvx, Kz = K
    Kp = Kvx + Kix / P.R
    Ki = -Kz
    Kd = P.C * (Kix - P.rC * Kvx)
    N = 1.0 / (P.rC * P.C)
    return np.array([Kp, Ki, Kd, N, 1.0, 0.0, Kb])


def c_lqi_freq(K, w, Vo=V_SYN, P=PLANT):
    """Output-error compensator generated by the full-state law, Eq. (31)."""
    lin = linearize(Vo, 0.0, P)
    Kx = K[None, :2]
    out = np.empty(len(w), complex)
    for k, wk in enumerate(w):
        Rv = np.linalg.solve(1j * wk * np.eye(2) - lin.A, lin.Bd)
        out[k] = (Kx @ Rv)[0, 0] / (lin.Cy @ Rv)[0, 0] - K[2] / (1j * wk)
    return out


def c_pidf_freq(theta, w):
    Kp, Ki, Kd, N = theta[:4]
    s = 1j * np.asarray(w)
    return Kp + Ki / s + Kd * N * s / (s + N)


def realization_audit(K, Kb=1.0, P=PLANT):
    """Coefficient residual and max relative frequency-domain error."""
    th = pidf_map(K, Kb, P)
    # coefficient identity of Eq. (30): Ki_x/R + (Ki_x C s + Kv_x)/(1 + rC C s)
    # = Kp + Kd N s/(s+N)  <=>  polynomial identity in s
    Kix, Kvx, _ = K
    lhs = np.polyadd(np.polymul([Kix / P.R], [P.rC * P.C, 1.0]), [Kix * P.C, Kvx])
    rhs = np.polyadd(np.polymul([th[0]], [P.rC * P.C, 1.0]),
                     [th[2] * th[3] * P.rC * P.C, 0.0])
    coef_res = float(np.max(np.abs(lhs - rhs)))
    w = np.logspace(-1, 8, 4000)
    a = c_lqi_freq(K, w, P=P)
    b = c_pidf_freq(th, w)
    rel = float(np.max(np.abs(a - b) / np.abs(a)))
    return coef_res, rel


def return_difference(design: LQIDesign, n=12000):
    """min_w |1 + L_K(jw)| of the full-state augmented loop, Eq. (22)."""
    Aa, Ba, _ = augmented()
    w = np.logspace(-2, 8, n)
    L = np.array([(design.K[None, :] @ np.linalg.solve(1j * wk * np.eye(3) - Aa, Ba))[0, 0]
                  for wk in w])
    rd = np.abs(1 + L)
    # phase margin at unit crossover
    idx = np.where(np.diff(np.sign(np.abs(L) - 1)))[0]
    pm = float(180 + np.degrees(np.angle(L[idx[-1]]))) if len(idx) else np.inf
    return float(rd.min()), pm
