"""Generate docs/isa/numbers.tex and docs/isa/tables/*.tex from the archived JSON.

No number of the manuscript is typed by hand: every macro below is read from
results/cmo/formula_first.json or results/cmo/analysis.json.
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, 'results', 'cmo')
DOC = os.path.join(ROOT, 'docs', 'isa')
sys.path.insert(0, ROOT)


def sci(x, d=3):
    if x == 0:
        return '0'
    e = int(np.floor(np.log10(abs(x))))
    m = x / 10 ** e
    return f'{m:.{d}f}\\times10^{{{e}}}'


def num(x, d=4):
    return f'{x:.{d}f}'


def main():
    ff = json.load(open(os.path.join(RES, 'formula_first.json')))
    an = json.load(open(os.path.join(RES, 'analysis.json')))
    M = {}
    c1 = ff['ccm'][0]
    M['CCMmargin'] = f"\\SI{{{1e3 * c1['margin']:.2f}}}{{mA}} (\\SI{{{100 * c1['margin'] / c1['Icrit']:.2f}}}{{\\percent}} of $I_{{crit}}$)"
    M['CCMratio'] = f"{c1['Rcrit_over_R']:.3f}"
    anc = an['switched']['Bryson anchor (xi0)']
    M['DCMone'] = f"\\SI{{{100 * anc['dcm_w1']:.2f}}}{{\\percent}}"
    M['ETAone'] = f"\\SI{{{100 * anc['eta_w1']:.2f}}}{{\\percent}}"
    resmax = max(max(abs(v['res_pct']), *[abs(w) for w in v['res_windows']]) for v in an['switched'].values())
    M['RESmax'] = f"${sci(resmax, 1)}\\,\\%$"
    lin = ff['linear_24V']
    A = lin['A']
    M['Aa'], M['Ab'], M['Ac'], M['Ad'] = [f'{v:.4f}' for v in (A[0][0], A[0][1], A[1][0], A[1][1])]
    M['Bd'] = f"{lin['Bd'][0]:.0f}"
    M['Cya'], M['Cyb'] = f"{lin['Cy'][0]:.7f}", f"{lin['Cy'][1]:.7f}"
    a = ff['anchor']
    M['Qa'], M['Qb'], M['Qc'] = f"{a['Q'][0]:.8f}", f"{a['Q'][1]:.8f}", f"{a['Q'][2]:.4f}"
    M['Rd'] = f"{a['Rd']:.8f}"
    M['Ka'], M['Kb'], M['Kc'] = f"{a['K'][0]:.8f}", f"{a['K'][1]:.8f}", f"{a['K'][2]:.8f}"
    M['CAREres'] = f"${sci(a['care_res_rel'], 2)}$"
    p = sorted(a['poles'], key=lambda z: z[1])
    M['Poles'] = f"${p[1][0]:.2f}$ and ${p[2][0]:.2f}\\pm j{abs(p[2][1]):.2f}$\\,rad/s"
    th = a['theta']
    M['ThA'], M['ThB'], M['ThC'], M['ThG'] = f'{th[0]:.10f}', f'{th[1]:.7f}', f"{sci(th[2], 7)}".join('$$'), f'{th[6]:.3f}'
    M['FreqErr'] = f"${sci(a['freq_rel_error'], 2)}$"
    M['RDmin'] = f"{a['min_return_difference']:.6f}"
    M['PMdeg'] = f"\\SI{{{a['phase_margin_deg']:.2f}}}{{\\degree}}"
    L = ff['anchor_lmi']
    M['AlphaCert'] = f"{L['alpha_cert']:.4f}"
    M['ZetaCert'] = f"{L['zeta_cert']:.7f}"
    M['Dmin'] = f"{L['d_range'][0]:.7f}"
    M['Dmax'] = f"{L['d_range'][1]:.7f}"
    eq = ff['equivalence']
    for k, name in (('nominal_ip0', 'EqNom'), ('load_pulse_0p5A', 'EqLoad'), ('R_plus20pct', 'EqR'),
                    ('L_minus20_rL_Ron_x2', 'EqL'), ('C_plus20pct', 'EqC')):
        M[name] = f"${sci(eq[k]['max_dvo'], 1)}$\\,V" if eq[k]['max_dvo'] < 1e-6 else f"\\SI{{{eq[k]['max_dvo']:.3f}}}{{V}}"
        M[name + 'Sat'] = f"\\SI{{{100 * eq[k]['sat_fraction']:.1f}}}{{\\percent}}"
    extra = os.path.join(RES, 'numbers_extra.json')
    if os.path.exists(extra):
        M.update(json.load(open(extra)))
    with open(os.path.join(DOC, 'numbers.tex'), 'w') as f:
        f.write('% generated by scripts/cmo_numbers.py -- do not edit\n')
        for k, v in M.items():
            f.write(f'\\newcommand{{\\{k}}}{{{v}}}\n')
    # Table: transfer functions and CCM screen
    os.makedirs(os.path.join(DOC, 'tables'), exist_ok=True)
    with open(os.path.join(DOC, 'tables', 'tab_tf.tex'), 'w') as f:
        f.write('\\begin{table*}[t]\n\\centering\n\\caption{Equilibria, monic $\\Delta(s)$, $G_{vd}$ numerator and stationary conduction screen at the three commanded levels (nominal load, $i_p=0$). $\\omega_z=1/(r_CC)=\\SI{2e5}{rad/s}$ at every level.}\n\\label{tab:tf}\n\\footnotesize\n')
        f.write('\\begin{tabular}{@{}rrrrrllrrrr@{}}\n\\toprule\n')
        f.write('$V_o$ (V) & $I_{L,0}$ (A) & $d_0$ & $\\rho_0$ ($\\Omega$) & $E_d$ (V) & $\\Delta(s)/(LC(R+r_C))$ & $G_{vd}$ numerator & $\\Delta I_{L,pp}$ (A) & $I_{crit}$ (A) & $\\bar I_L-I_{crit}$ (A) & $R_{crit}/R$\\\\\n\\midrule\n')
        for tf, c in zip(ff['transfer_functions'], ff['ccm']):
            d = tf['den_monic']; n = tf['Gvd_num']
            f.write(f"{tf['Vo']:.0f} & {tf['IL0']:.1f} & {tf['d0']:.6f} & {tf['rho0']:.6f} & {tf['Ed']:.3f} & "
                    f"$s^2+{d[1]:.2f}s+{sci(d[2], 5)}$ & ${sci(n[0], 5)}s+{sci(n[1], 5)}$ & "
                    f"{c['dIpp']:.4f} & {c['Icrit']:.4f} & {c['margin']:.4f} & {c['Rcrit_over_R']:.3f}\\\\\n")
        f.write('\\bottomrule\n\\end{tabular}\n\\end{table*}\n')
    print(f'{len(M)} macros written')


if __name__ == '__main__':
    main()
